[tool.poetry]
name = "digdir-api"
version = "0.0.1"
description = ""
authors = ["pbencze <paul.bencze@nav.no>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.61.1"
python-dotenv = "^0.14.0"
concepttordf = "^1.0.0-rc.7"
datacatalogtordf = "1.0.3"
uvicorn = "^0.12.1"
requests = "^2.23.0"
pytest = "^6.0.1"



[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["deetly"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
